float getFakeWeight(float pt, float eta){

  return 0.015;
}

void makeEFakePh(std::string treeNmae="Wg_strong") {
  // Example of Root macro to copy a subset of a Tree to a new Tree
  // Only selected entries are copied to the new Tree.
  // The input file has been generated by the program in $ROOTSYS/test/Event
  // with   Event 1000 1 99 1
  //Author: Rene Brun
  
  //gSystem->Load("$ROOTSYS/test/libEvent");

  //Get old file, old tree and set top branch address
  //TFile *oldfile = new TFile("/eos/atlas/atlascerngroupdisk/phys-exotics/jdm/vbfinv/v37Loose/v37ALoose/Z_strong.root");
  std::string oldfileNmae="/tmp/v41Agam/"+treeNmae+".root";
  TFile *oldfile = new TFile(oldfileNmae.c_str());
  std::string oldtreeNmae=treeNmae+"Nominal";
  TTree *oldtree = (TTree*)oldfile->Get(oldtreeNmae.c_str());
  Long64_t nentries = oldtree->GetEntries();

  std::vector<float> copy_el_pt;
  std::vector<float> copy_el_phi;
  std::vector<float> copy_el_eta;
  std::vector<float> copy_baseel_pt;
  std::vector<float> copy_baseel_phi;
  std::vector<float> copy_baseel_eta;
  
  std::vector<float> *el_pt=new std::vector<float>();
  std::vector<float> *el_phi=new std::vector<float>();  
  std::vector<float> *el_eta=new std::vector<float>();
  std::vector<float> *baseel_pt=new std::vector<float>();
  std::vector<float> *baseel_phi=new std::vector<float>();  
  std::vector<float> *baseel_eta=new std::vector<float>(); 
  std::vector<float> *ph_phi=new std::vector<float>();
  std::vector<float> *ph_eta=new std::vector<float>();
  std::vector<float> *ph_pt=new std::vector<float>();
  std::vector<float> *jet_phi=new std::vector<float>();
  std::vector<float> *jet_eta=new std::vector<float>();
  std::vector<float> *jet_pt=new std::vector<float>();  
  int runNumber   = 0;
  int n_baseel   = 0;
  int n_el   = 0;
  int n_el_w   = 0;
  int n_ph   = 0;
  int n_basemu   = 0;
  float met_truth_et=0;
  float met_tst_et=0;
  float met_tst_nolep_et=0;
  float met_tst_phi=0;
  float met_tst_nolep_phi=0;  
  float SherpaVTruthPt=0;
  float truth_V_dressed_pt=0;
  double truth_jj_mass=0;
  float w=0.0;
  double met_tst_j1_dphi =0;
  double met_tst_j2_dphi =0;
  double met_tst_nolep_j1_dphi =0;
  double met_tst_nolep_j2_dphi =0;  
  oldtree->SetBranchAddress("w",&w);
  oldtree->SetBranchAddress("runNumber",&runNumber);
  oldtree->SetBranchAddress("n_baseel",&n_baseel);
  oldtree->SetBranchAddress("n_el",&n_el);
  oldtree->SetBranchAddress("n_ph",&n_ph);
  oldtree->SetBranchAddress("el_pt",&el_pt);
  oldtree->SetBranchAddress("el_eta",&el_eta);
  oldtree->SetBranchAddress("el_phi",&el_phi);
  oldtree->SetBranchAddress("baseel_pt",&baseel_pt);
  oldtree->SetBranchAddress("baseel_eta",&baseel_eta);
  oldtree->SetBranchAddress("baseel_phi",&baseel_phi);
  
  oldtree->SetBranchAddress("jet_pt",&jet_pt);
  oldtree->SetBranchAddress("jet_eta",&jet_eta);
  oldtree->SetBranchAddress("jet_phi",&jet_phi);
  oldtree->SetBranchAddress("met_tst_j1_dphi",&met_tst_j1_dphi);
  oldtree->SetBranchAddress("met_tst_j2_dphi",&met_tst_j2_dphi);
  oldtree->SetBranchAddress("met_tst_nolep_j1_dphi",&met_tst_nolep_j1_dphi);
  oldtree->SetBranchAddress("met_tst_nolep_j2_dphi",&met_tst_nolep_j2_dphi);  
  
  oldtree->SetBranchAddress("ph_pt",&ph_pt);
  oldtree->SetBranchAddress("ph_eta",&ph_eta);
  oldtree->SetBranchAddress("ph_phi",&ph_phi);
  oldtree->SetBranchAddress("n_el_w",&n_el_w);
  oldtree->SetBranchAddress("n_basemu",&n_basemu);
  oldtree->SetBranchAddress("met_truth_et",&met_truth_et);
  oldtree->SetBranchAddress("met_tst_et",&met_tst_et);
  oldtree->SetBranchAddress("met_tst_nolep_et",&met_tst_nolep_et);
  oldtree->SetBranchAddress("met_tst_phi",&met_tst_phi);
  oldtree->SetBranchAddress("met_tst_nolep_phi",&met_tst_nolep_phi);
  
  oldtree->SetBranchAddress("truth_jj_mass",&truth_jj_mass);
  oldtree->SetBranchAddress("truth_V_dressed_pt",&truth_V_dressed_pt);
  oldtree->SetBranchAddress("SherpaVTruthPt",&SherpaVTruthPt);

  //Create a new file + a clone of old tree in new file
  std::string outfileName="/tmp/small"+treeNmae+".root";
  TFile *newfile = new TFile(outfileName.c_str(),"recreate");
  TTree *newtree = oldtree->CloneTree(0);
  newtree->SetName("EFakePhNominal");
  newtree->SetTitle("EFakePhNominal");  
  TVector3 met,met_nolep,newel,jet1,jet2;
  for (Long64_t i=0;i<nentries; i++) {
    if((i%100000)==0) std::cout <<"evt: " << i << std::endl;
    oldtree->GetEntry(i); //n_baseel==0 && n_basemu==0 
    if (n_ph==0 && n_el==1 && n_el_w==1 && n_baseel==1){
      n_ph=1;
      n_el=0;
      n_el_w=0;
      n_baseel=0;
      ph_pt->push_back(el_pt->at(0));
      ph_eta->push_back(el_eta->at(0));
      ph_phi->push_back(el_phi->at(0));
      // acceptance cuts
      if(fabs(ph_eta->at(0))>1.37 && fabs(ph_eta->at(0))<1.52) continue;
      if(ph_pt->at(0)<10e3) continue;
      
      //add electron
      w*=getFakeWeight(ph_pt->at(0),ph_eta->at(0));
      newel.SetPtEtaPhi(ph_pt->at(0),0.0,ph_phi->at(0));
      met.SetPtEtaPhi(met_tst_et,0.0,met_tst_phi);
      met_nolep.SetPtEtaPhi(met_tst_nolep_et,0.0,met_tst_nolep_phi);
      //met+=newel;
      //met_nolep+=newel;
      //met_tst_et=met.Pt();
      //met_tst_phi=met.Phi();
      //met_tst_nolep_et=met_nolep.Pt();
      //met_tst_nolep_phi=met_nolep.Phi();
      met_tst_nolep_et=met_tst_et;
      met_tst_nolep_phi=met_tst_phi;

      if(jet_pt->size()>1){
	jet1.SetPtEtaPhi(jet_pt->at(0),jet_eta->at(0),jet_phi->at(0));
	jet2.SetPtEtaPhi(jet_pt->at(1),jet_eta->at(1),jet_phi->at(1));
	met_tst_j1_dphi=fabs(jet1.DeltaPhi(met));
	met_tst_j2_dphi=fabs(jet2.DeltaPhi(met));
	met_tst_nolep_j1_dphi=fabs(jet1.DeltaPhi(met_nolep));
	met_tst_nolep_j2_dphi=fabs(jet2.DeltaPhi(met_nolep));	
      }
      
      el_pt->clear();
      el_eta->clear();
      el_phi->clear();
      baseel_pt->clear();
      baseel_eta->clear();
      baseel_phi->clear();      
      newtree->Fill();
    }else if (n_ph==0 && n_el==2 && n_baseel==2){
      for(unsigned iele=0; iele<2; ++iele){
	if(iele==0){
	  copy_el_pt = *el_pt;
	  copy_el_phi = *el_phi;
	  copy_el_eta = *el_eta;
	  copy_baseel_pt = *baseel_pt;
	  copy_baseel_phi = *baseel_phi;
	  copy_baseel_eta = *baseel_eta;
	}
	n_ph=1;
	n_el=1;
	n_el_w=1;
	n_baseel=1;
	ph_pt->push_back(copy_el_pt.at(iele));
	ph_eta->push_back(copy_el_eta.at(iele));
	ph_phi->push_back(copy_el_phi.at(iele));

	// rm crack
	if(fabs(ph_eta->at(0))>1.37 && fabs(ph_eta->at(0))<1.52) continue;
	if(ph_pt->at(0)<10e3) continue;
	
	//add electron
	w*=getFakeWeight(ph_pt->at(0),ph_eta->at(0));
	newel.SetPtEtaPhi(ph_pt->at(0),0.0,ph_phi->at(0));
	met.SetPtEtaPhi(met_tst_et,0.0,met_tst_phi);
	met_nolep.SetPtEtaPhi(met_tst_nolep_et,0.0,met_tst_nolep_phi);
	//met+=newel;
	met_nolep+=newel;
	//met_tst_et=met.Pt();
	//met_tst_phi=met.Phi();
	met_tst_nolep_et=met_nolep.Pt();
	met_tst_nolep_phi=met_nolep.Phi();

	if(jet_pt->size()>1){
	  jet1.SetPtEtaPhi(jet_pt->at(0),jet_eta->at(0),jet_phi->at(0));
	  jet2.SetPtEtaPhi(jet_pt->at(1),jet_eta->at(1),jet_phi->at(1));
	  met_tst_j1_dphi=fabs(jet1.DeltaPhi(met));
	  met_tst_j2_dphi=fabs(jet2.DeltaPhi(met));
	  met_tst_nolep_j1_dphi=fabs(jet1.DeltaPhi(met_nolep));
	  met_tst_nolep_j2_dphi=fabs(jet2.DeltaPhi(met_nolep));	
	}

	el_pt->clear(); el_pt->push_back(copy_el_pt.at(iele));
	el_eta->clear(); el_eta->push_back(copy_el_eta.at(iele));
	el_phi->clear(); el_phi->push_back(copy_el_phi.at(iele));
	baseel_pt->clear(); baseel_pt->push_back(copy_baseel_pt.at(iele));
	baseel_eta->clear(); baseel_eta->push_back(copy_baseel_eta.at(iele));
	baseel_phi->clear();  baseel_phi->push_back(copy_baseel_phi.at(iele));
	
	newtree->Fill();
      }
    }
    //event->Clear();
  }
  newtree->Print();
  newtree->AutoSave();
  delete oldfile;
  delete newfile;
}
